// Produce a standalone stylesheet for the design-sync bundle.
//
// The app's real stylesheet is src/app/globals.css, but it can't ship as-is:
//   * `@import "tailwindcss"` and `@theme inline {…}` only resolve inside the
//     app's Tailwind build. The components use exactly one Tailwind utility
//     (`sr-only`) — cheaper to define it here than to run Tailwind.
//   * `--font-lora` is injected at runtime by next/font in app/layout.tsx, and
//     Pretendard is loaded by a <link> tag there. Neither reaches a preview
//     card, so both families are pulled in as remote @imports instead.
//
// Everything else — every token, every .briefly-* class, the dark theme — is
// copied verbatim from globals.css so the catalog can never drift from the app.
//
// Run: node .design-sync/styles/prepare-css.mjs   (wired as cfg.buildCmd)

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG_DIR = resolve(HERE, '..', '..');
const SRC = join(PKG_DIR, 'src', 'app', 'globals.css');
const OUT_DIR = join(PKG_DIR, '.design-sync', '.cache');
const OUT = join(OUT_DIR, 'newsboy.css');

let css = readFileSync(SRC, 'utf8');

// 1. Drop the Tailwind entry import.
css = css.replace(/^@import\s+["']tailwindcss["'];?\s*$/m, '');

// 2. Drop the `@theme inline { … }` block (Tailwind-only; it re-exports tokens
//    the components never reference by their Tailwind names).
css = css.replace(/@theme\s+inline\s*\{[^{}]*\}\s*/g, '');

const HEADER = `/* GENERATED by .design-sync/styles/prepare-css.mjs — do not edit.
   Source of truth: src/app/globals.css */

/* Lora — app/layout.tsx loads it via next/font/google, which doesn't run here. */
@import url('https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap');
/* Pretendard — app/layout.tsx loads this exact URL via a <link> tag. */
@import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.css');

:root {
  /* next/font names the family at build time; standalone we reference it directly. */
  --font-lora: 'Lora';
}
`;

const FOOTER = `
/* The single Tailwind utility the components use (visually-hidden label). */
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT, HEADER + css.trimStart() + FOOTER);
console.error(`prepare-css: wrote ${OUT}`);
